/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'TaskWorker': EventHandler<never, never>
    'SubmitTask': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'task.submitted'; data: never }>
    'GetTaskStatus': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
}